services:
  mongodb:
    image: mongo:6.0
    container_name: finance_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - finance_network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: finance_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb
    networks:
      - finance_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: finance_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - finance_network

networks:
  finance_network:
    driver: bridge

volumes:
  mongo_data:
    driver: local
